version: "3.8"

services:
  mastchain-ais:
    image: ghcr.io/c-man-the-man/mastchain-ais:latest
    container_name: mastchain-ais
    restart: unless-stopped

    devices:
      - /dev/bus/usb:/dev/bus/usb

    ports:
      - "8100:8100"

    volumes:
      - ./config.json:/data/config.json:ro
      - mastchain_data:/data

    environment:
      TZ: YOUR-TIMEZONE

    command: -C /data/config.json -H https://api.mastchain.io/api/upload USERPWD YOUR-MASTCHAIN-EMAIL:TOKEN INTERVAL 60 -p 0 -v 30 -N 8100 share_loc off use_gps on

volumes:
  mastchain_data:
    name: mastchain_data
